zakodium-oss/react-science

- src/layout/Toolbar.tsx
close: allow to pass "undefined" in Toolbar.Item #13
> fix: add ReactFragment, boolean and null to Toolbar

- src/app/components/MeasurementExplorer.tsx
Display some information in the dropdown (it uses the variable id, label and units).  The id is for avoiding confusion between variables with the same label (say both are "Transmittance").
But should we lowercase the label, uppercasing the first letter, or leave them as they appear in the files?
**Before**
**After changes**
> refactor(MeasurementExplorer): dropdown items

- src/components/index.ts
- src/components/spinner/FullSpinner.tsx
- src/components/spinner/index.ts
- src/pages/big-map/MainLayout.tsx
- stories/components/fullspinner.stories.tsx
Close: https://github.com/zakodium-oss/analysis-ui-components/issues/382
> feat: add spinner while fetching data

- src/app-data/state/appState.tsx
- src/app-data/state/appStateActions.ts
- src/app-data/state/producers/appStateProducer.ts
- src/pages/big-map/MainLayout.tsx
- src/pages/big-map/helpers/loadFiles.ts
- src/pages/demo/MainLayout.tsx
- src/pages/demo/helpers/loadFiles.ts
Closes: https://github.com/zakodium-oss/analysis-ui-components/issues/408
> fix: only show spinner when data is loading

- src/components/forms/Input.tsx
- src/components/forms/context/FieldsContext.tsx
- src/components/forms/context/index.ts
- src/components/forms/index.ts
- src/components/index.ts
- stories/components/input.stories.tsx
Parts of: https://github.com/zakodium-oss/analysis-ui-components/issues/346
> feat add input

- src/components/dropdown-menu/MenuItems.tsx
closes: https://github.com/zakodium-oss/react-science/issues/445
> fix: stop click event propagation on MenuItem

- package-lock.json
- src/components/split-pane/SplitPane.tsx
closes : https://github.com/zakodium-oss/react-science/issues/450
the problem was in `parseSize` function
I had two solution
- Update the old regex :
```js
const [, value, type] = /(?<value>^\d+\.?\d+)(?<type>.+)$/.exec(
initialSize,
) as unknown as [string, string, SplitPaneType];
```
- Get float from the parsed string then extract type by deleting the rest
```js
const value = Number.parseFloat(initialSize);
const type = initialSize.replace(/[\d .]/g, '') as SplitPaneType;
```
I prefer the second one, which is implemented in this PR
> fix: parse decimal size

- src/components/split-pane/SplitPane.tsx
- src/pages/demo/MainLayout.tsx
- stories/components/accordion.stories.tsx
- stories/components/modal.stories.tsx
- stories/components/split-pane.stories.tsx
> fix: splitter not observe 'size' and 'closed' values changes

- src/components/modal/Modal.tsx
-  https://github.com/zakodium-oss/react-science/issues/459
> fix: modal should not take space in the layout if no nodes inside it

- src/components/hooks/useOnClickOutside.ts
- src/components/modal/ConfirmModal.tsx
- src/components/modal/Modal.tsx
- src/components/modal/useDialog.ts
- src/components/root-layout/Portal.tsx
- src/components/root-layout/RootLayoutContext.tsx
- stories/components/select.stories.tsx
Modal now create a root layout to ensure Select components opens in front of the modal instead of behind.
> fix: modal generate a new portal context

- src/components/hooks/useOnOff.ts
- src/components/modal/ConfirmModal.tsx
- src/components/modal/Modal.tsx
- src/components/modal/useDialog.ts
- stories/components/modal.stories.tsx
This is important when the children measure their size dynamically when
they are mounted. The OCL editor does it.
> fix: only render modal children after calling showModal

- src/components/toolbar/Toolbar.tsx
- stories/components/toolbar.stories.tsx
refactor: `intent` and `disabled` props at toolbar level will be overridden with the item props once it is defined
at item level
> feat: add a 'disabled' option to Toolbar.Item

- src/components/root-layout/RootLayout.tsx
This leads to random crashes because browser translation manipulates the
DOM in a way that React can be confused.
> fix: disable auto-translate of applications

- src/components/hooks/useSelect.tsx
- stories/components/select.stories.tsx
Improve the useSelect hook :
- It accepts a `defaultSelectedItem` property.
- You can specify which object serves as the label in two ways:
- Using the `itemTextKey` property, which accepts only keys where the value type is a string.
- Using the `getItemText` function, which takes an item as a parameter and returns a string.
> feat: improve use select hook

- src/components/root-layout/RootLayout.tsx
- src/pages/demo/App.tsx
Set the portal container to the root layout div so we can open dialogs when in fullscreen
> fix: add blueprint provider to root layout

- src/components/table/Table.tsx
- src/components/table/TableHeader.tsx
- stories/components/table.stories.tsx
> feat: add sticky table header option

- src/components/button/Button.tsx
We have a warning in the console from Blueprint.js when the button component is used with empty tooltip content. To prevent this, we should disable the tooltip if its content is empty, which makes sense since an empty tooltip should be avoided.
I believe Blueprint.js should disable the tooltip by default if the content is empty.
> fix: disable button tooltips with empty content

- src/components/hooks/useSelect.tsx
- stories/components/select.stories.tsx
In some cases, we need more than just text in the menu items, we require additional elements, as seen in the workspaces dropdown menu in NMRium. Therefore, I suggest enhancing the useSelect hook to support custom item rendering. I don't want to replace the entire MenuItem; I just need the ability to customize its content.
> feat: improve useSelect hook item render

- src/components/toolbar/Toolbar.tsx
Closes: https://github.com/zakodium-oss/react-science/issues/725
> fix: toolbar popover item should have backdrop to avoid interactions outside of it when it is open

- src/components/color-picker/react-color/helpers/color.js
I updated the `toState` function which is responsible for managing the color on the color picker component to include the alpha channel in the hex color when the alpha is less than 100%.
- Hex format is 8 characters (#RRGGBBAA) for colors with transparency.
- In case the (alpha = 100%), the hex format remains 6 characters (#RRGGBB).
> fix: include alpha in hex code for semi-transparent colors

- src/components/activity_bar/activity_bar.tsx
- src/components/activity_bar/index.ts
- src/components/index.ts
- src/components/toolbar/Toolbar.tsx
- src/components/toolbar/toolbarContext.ts
- stories/components/activity_bar.stories.tsx
- stories/components/toolbar.stories.tsx
The commits are intended to be rebased.
> feat: activity bar and fixes

- src/components/toolbar/Toolbar.tsx
- stories/components/accordion.stories.tsx
- stories/components/toolbar.stories.tsx
- **fix: do not expose the isPopover prop**
- **fix(toolbar): do not pass item props in onClick callback**
- **docs(toolbar): add JSDoc to explain the `popoverInteractionKind` prop**
Closes: https://github.com/zakodium-oss/react-science/issues/704
> fix: review toolbar item props

- src/components/button/Button.tsx
Make sure it's consistent across button variants, and by default results in the same height as inputs.
The height of the different variants of buttons are now consistent with the sizes observed in blueprintjs' documentation.
Closes: https://github.com/zakodium-oss/react-science/issues/743
> fix(button): correct default height of buttons

- src/components/table/table_header.tsx
- src/components/table/table_header_cell.tsx
- src/components/table/table_root.tsx
- stories/components/table.stories.tsx
- stories/react-table.d.ts
Example of use case: use a fixed layout table and set the width of certain columns by setting the header's width
> feat: add renderHeaderCell prop to `Table` component

- src/components/table/table_body.tsx
- src/components/table/table_root.tsx
- src/components/table/table_utils.ts
- src/components/table/use_table_scroll.ts
- stories/components/table.stories.tsx
Closes: https://github.com/zakodium-oss/react-science/issues/815
> feat(Table): add scrollToRowRef prop to the Table component

- src/components/info-panel/InfoPanel.tsx
Do this can work ? I'm only checking if the value is true or false, to map this to "yes" or "no".
> fix: allow to search with `yes` or `no`

- stories/components/menus.stories.tsx
Attention! its a docs not a fix
> fix(Menus): do not overflow divider

- .storybook/preview.ts
- README.md
- package-lock.json
- package.json
- src/pages/demo/App.tsx
- stories/components/select.stories.tsx
- **chore: move @blueprintjs/select to peer dependencies**
- **fix: import blueprint-select css in storybook and app setups**
- **docs: complete global css setup in readme**
To be rebased.
> chore: move @blueprintjs/select to peer dependencies and misc

- src/components/button/Button.tsx
- src/components/toolbar/Toolbar.tsx
Blueprintjs prints a warning about the prop having no effect in that case.
Closes: https://github.com/zakodium-oss/react-science/issues/859
> fix: remove targetProps where renderTarget is used

- src/components/split-pane/SplitPane.tsx
Closes: https://github.com/zakodium-oss/react-science/issues/858
> fix: ensure content of split bar does not overflow

- src/components/table/table_root.tsx
removes a emotion warning about unsafe usage in SSR.
Closes: https://github.com/zakodium-oss/react-science/issues/854
> refactor(Table): use first-of-type instead of first-child

- package-lock.json
- package.json
- src/components/table/index.ts
- src/components/table/reorder_rows/draggable_row_context.ts
- src/components/table/reorder_rows/draggable_row_tr.tsx
- src/components/table/reorder_rows/drop_indicator.tsx
- src/components/table/reorder_rows/dropped_item_context.ts
- src/components/table/reorder_rows/dropped_item_provider.tsx
- src/components/table/reorder_rows/index.ts
- src/components/table/reorder_rows/item_data.ts
- src/components/table/reorder_rows/item_order_context.ts
- src/components/table/reorder_rows/item_order_provider.tsx
- src/components/table/reorder_rows/table_drag_row_handler.tsx
- src/components/table/reorder_rows/use_drop_monitor.ts
- src/components/table/table_body.tsx
- src/components/table/table_root.tsx
- src/components/table/table_row_cell.tsx
- src/components/table/table_utils.ts
- stories/components/table.reorder.stories.tsx
- stories/components/table.stories.tsx
- Add `getTdProps` prop which allows to customize the attributes passed to the `<td>` elements, including style. This is useful for example to center content within a cell as this can not easily be done in tables based on the cell's children only.
- Add `onRowOrderChanged` callback which is called when a manual reordering operation is finished, with the data items in their new order.
- Add `renderRowPreview` to customize the content of the dragged row's preview.
- Add `scrollableElementRef` prop which allows to pass an external reference to the element that should be auto-scrolled when reordering rows.
- Export new `TableDragRowHandler` for a good default drag handler that can be used in cell renderers.
Other new hooks and components which allow to customize the row reordering UI:
- …
> feat(Table): allow to pass custom td attributes and reorder rows

- src/components/fullscreen/fullscreen_context.provider.tsx
- src/components/root-layout/css-reset/customPreflight.ts
- src/components/root-layout/root_layout.tsx
- src/pages/demo/App.tsx
- stories/components/fullscreen.stories.tsx
BREAKING-CHANGE: FullScreenProvider now takes a render callback with the ref to attach to the element which can be displayed fullscreen. It no longer renders an additional styled div.
The RootLayout is now a fullscreenable element. It is no longer necessary to wrap it in a FullScreenProvider. Added a global CSS rule to make fullscreen elements' backdrop background color white.
Closes: https://github.com/zakodium-oss/react-science/issues/689
Note: It is not possible to add a margin to a fullscreen element so the stories are slightly different now.
I find it to make more sense to put the border on the element which is fullscreenable rather than a child of it.
Therefore there is no space outside the border anymore.
> feat: change FullScreenProvider API to not create additional div

- .stylelintrc.json
- src/components/pdnd.cts
- src/components/table/reorder_rows/draggable_row_tr.tsx
- src/components/table/reorder_rows/item_order_provider.tsx
- src/components/table/reorder_rows/use_drop_monitor.ts
- tsconfig.json
Given how @atlaskit/pragmatic-drag-and-drop publishes ESM in a non-native way, we have to trick TS into using the CJS build so that our build is compatible with native ESM.
Closes: https://github.com/zakodium-oss/react-science/issues/899
> fix: make sure build is natively compatible with ESM

- src/components/accordion/accordion.tsx
- src/components/accordion/accordion_context.ts
- src/components/accordion/accordion_context_provider.tsx
- src/components/accordion/accordion_context_utils.ts
- src/components/accordion/index.ts
- stories/components/accordion.stories.tsx
- stories/components/accordion_story_helpers.tsx
- stories/components/activity_bar.stories.tsx
Ref: https://github.com/zakodium/peak-by-peak/issues/360
BREAKING-CHANGE: The render callback parameter has changed to contain multiple properties instead of just the `isOpen` state. It can now be used to control the state of the item in which it is rendered. Click events in the toolbar no longer propagate to the header in order to prevent it from toggling if it is not wanted.
> feat(Accordion): improve renderToolbar API

- package-lock.json
- package.json
- src/components/fullscreen/fullscreen_context.provider.tsx
- src/components/root-layout/root_layout.tsx
- stories/components/fullscreen.stories.tsx
> Use a library to manage fullscreen APIs.
> Also add a `onToggleError` prop to the `FullScreenProvider` and `RootLayout` components.
>
> There is a behavior change with "stacked" fullscreen elements (like in the storybook). Now when you enter fullscreen a second time, it will first exit the previous fullscreen. I think it's fine. We don't (and probably shouldn't) use stacked fullscreens in real apps.
I'm not sure about the `onToggleError` prop. Another option is to make the `toggle()` function async, but then the user has to handle it otherwise it will be an unhandled rejection (which for example will trigger error monitors like Sentry).
> feat: improve fullscreen error handling

- src/components/table/table_root.tsx
Ref: https://github.com/zakodium/peak-by-peak/issues/375
> fix(Table): remove false positive warning about conflicting props

- src/components/activity_bar/activity_bar.tsx
- src/components/button/Button.tsx
- src/components/icon.tsx
- src/components/toolbar/Toolbar.tsx
- stories/components/activity_bar.stories.tsx
- **fix: correct toolbar button when blueprint css is in a layer**
- **refactor: simplify markup for activity item**
- **fix: make sure the toolbar buttons are properly centered when blueprint styles are in a layer.**
> fix: correct incompatibilities when blueprint stylesheet is in a css layer

- src/components/split_pane/split_pane.tsx
- stories/components/split_pane.stories.tsx
- **feat(SplitPane): add prop to unmount any invisible split pane side**
- **docs: add an example which uses a size in pixels, not percent**
> 927 splitpane do not render side when size is 0
