zakodium-oss/react-science

src/layout/Toolbar.tsx
=> feat resolve toolbar props

.storybook/preview-head.html, src/index.ts, src/layout/Modal.tsx, src/layout/RootLayout.tsx, src/layout/Toolbar.tsx, stories/modal.stories.tsx, stories/toolbar.stories.tsx
=> feat: set text from Toolbar to center

package.json, src/layout/Accordion.tsx, src/layout/context/AccordionContext.tsx, src/layout/hooks/useDoubleClick.tsx, stories/accordion.stories.tsx
close: #31
@lpatiny What do you think of this?
=> Feat-accordion-dc

src/layout/Accordion.tsx, src/layout/Header.tsx, src/layout/SplitPane.tsx, src/layout/Toolbar.tsx, src/layout/__tests__/accordion.test.tsx, stories/accordion.stories.tsx, stories/full.stories.tsx
=> Fix-errors-v1

src/index.ts, src/layout/Modal.tsx
add useOnOff, 
fix error on Modal
=> Fix-modals

src/app/App.tsx, src/layout/Accordion.tsx, src/layout/SplitPane.tsx, src/layout/context/AccordionContext.tsx, src/layout/hooks/useSplitPaneSize.tsx, stories/split.stories.tsx
Closes: https://github.com/cheminfo/analysis-ui-components/issues/84
=> fix: should not crashes if item not found

src/layout/Accordion.tsx, src/layout/DropZone.tsx, src/layout/Modal.tsx, src/layout/RootLayout.tsx, stories/layout.stories.tsx
I need to know the list of all the components which the user can pick from when declaring the layout. Also, I didn't get what was the component `BlueBackground` in the example of the layout provided.
I couldn't find a way to have a dynamic types for the properties.
=> feat: Render components from layout object

src/layout/RootLayout.tsx, src/layout/context/RootLayoutContext.tsx
Closes: https://github.com/zakodium-oss/analysis-ui-components/issues/116
=> Resolve error on ssr with document

.github/workflows/deploy.yml, vite.config.ts
Fixes: https://github.com/zakodium-oss/analysis-ui-components/issues/149
=> fix: specify base URL for gh-pages build

src/components/DropZone.tsx, stories/dropZone.stories.tsx
closes : https://github.com/zakodium-oss/analysis-ui-components/issues/164
=> DropZone Improvement

stories/IRPeaksPanel.stories.tsx, stories/measurementInfoPanel.stories.tsx, stories/measurementsPanel.stories.tsx
closes : https://github.com/zakodium-oss/analysis-ui-components/issues/183#event-6919847232
=> docs: group panels

.ncurc.json, package-lock.json, package.json, src/components/LayoutManager.tsx, src/components/RootLayout.tsx, src/components/context/data/processors/jcampProcessor.ts, src/components/hooks/useSplitPaneSize.tsx, tsconfig.json, vite.config.ts
BREAKING CHANGE: React >=v18 is now mandatory.
=> chore: update dependencies

package-lock.json, package.json, src/components/split-pane/SplitPane.tsx, src/components/split-pane/useSplitPaneSize.tsx, stories/components/split-pane.stories.tsx
closes https://github.com/zakodium-oss/analysis-ui-components/issues/209
=> refactor: split pane

src/components/split-pane/useSplitPaneSize.tsx
closes https://github.com/zakodium-oss/analysis-ui-components/issues/233
=> fix: split pan cursor in px type

src/app/App.tsx
closes https://github.com/zakodium-oss/analysis-ui-components/issues/221
=> feat: use the MeasurementExplorer component in the app

package-lock.json, src/components/Tabs.tsx, stories/components/tabs.stories.tsx
closes https://github.com/zakodium-oss/analysis-ui-components/issues/215
I implemented a basic solution which is adding scroll on overflow.
=> feat: many tab scroll

package-lock.json, package.json, src/app/data/__tests__/getIVMeasurement.test.ts, src/app/data/loaders/biologicLoader.ts
Seems to be accepting the biologic-converter data, but it errors out :
```
Uncaught TypeError: value is undefined
convertString react-plot.js:4246
convertValue react-plot.js:4251
usePosition react-plot.js:4157
Line react-plot.js:4385
React 11
workLoop scheduler.development.js:266
flushWork scheduler.development.js:239
performWorkUntilDeadline scheduler.development.js:533
js scheduler.development.js:571
js
```
=> test: added biologic test back

src/app/context/appState.tsx, src/app/context/load.ts
closes : https://github.com/zakodium-oss/analysis-ui-components/issues/250
=> feat: select measurement on drop

src/app/context/appState.tsx
closes https://github.com/zakodium-oss/analysis-ui-components/issues/270
=> feat: accept many measurement in each kind

README.md
Very useful readme. Just suggesting to modify a few sentences.
=> chore(readme): re-wording a few sentences

src/app/App.tsx
closes https://github.com/zakodium-oss/analysis-ui-components/issues/253
=> feat: add info panel to app

src/app/components/MeasurementsPanel.tsx, stories/app/measurements/measurements-panel.stories.tsx
closes https://github.com/zakodium-oss/analysis-ui-components/issues/251
=> Measurement panel story

README.md, src/app/App.tsx, src/app/hooks/useHashSearchParams.ts, src/app/main.tsx
Closes: https://github.com/zakodium-oss/analysis-ui-components/issues/258
=> refactor: use hash params instead of search params

package-lock.json, package.json, src/app/data/loaders/biologicLoader.ts, src/components/menu/DropdownMenu.tsx, stories/components/dropdown.stories.tsx
Split the prev PR into several smaller ones so it doesn't fall too much behind the main branch.
=> feat (biologic): default x-y for (some) experiments

src/app/data/loaders/jcampLoader.ts, src/app/data/loaders/proprietary/agilent/cary500Loader.ts, src/app/data/loaders/spcLoader.ts, src/app/data/loaders/wdfLoader.ts
* refactor some regex
* replaced `any` types in a few loaders
=> refactor(loaders): remove some warnings 

src/components/menu/DropdownMenu.tsx, src/components/menu/useContextMenuPlacement.ts, stories/components/dropdown.stories.tsx
close: https://github.com/zakodium-oss/analysis-ui-components/issues/260
=> feat: add context menu dropdown

src/app-data/appState.tsx, src/app-data/data.helpers.ts, src/pages/big-map/App.tsx, src/pages/demo/App.tsx
closes https://github.com/zakodium-oss/analysis-ui-components/issues/269
=> refactor: save only selectedKind

src/app-data/DataState.ts, src/app-data/__tests__/getGCMSMeasurement.test.ts, src/app-data/__tests__/getHPLCMeasurement.test.ts, src/app-data/__tests__/getIRMeasurement.ts, src/app-data/__tests__/getIVMeasurement.test.ts, src/app-data/__tests__/loadMeasurements.test.ts, src/app-data/appState.tsx, src/app-data/data.helpers.ts, src/app-data/enhancers/enhance.ts, src/app-data/loadMeasurements.ts, src/app-data/loaders/biologicLoader.ts, src/app-data/loaders/cdfLoader.ts, src/app-data/loaders/jcampLoader.ts, src/app-data/loaders/proprietary/agilent/__tests__/cary500Loader.test.ts, src/app-data/loaders/proprietary/agilent/cary500Loader.ts, src/app-data/loaders/spcLoader.ts, src/app-data/loaders/wdfLoader.ts
closes https://github.com/zakodium-oss/analysis-ui-components/issues/280
=> refactor: simplify ADD_MEASUREMENTS

playwright-base.config.ts, tests/app/toolbar.test.ts
Fixes: https://github.com/zakodium-oss/analysis-ui-components/issues/333
=> test: avoid redirection

src/app-data/appState.tsx, src/app-data/data.helpers.ts
closes https://github.com/zakodium-oss/analysis-ui-components/issues/342
=> fix: add measurements

src/components/fullscreen/FullscreenContext.tsx
closes https://github.com/zakodium-oss/analysis-ui-components/issues/341
=> refactor: add safari fullscreen case

src/app-data/appState.tsx, src/app-data/data.helpers.ts, src/app/explorer/MeasurementPlot.tsx, src/app/panels/MeasurementPanel.tsx, src/pages/big-map/MainLayout.tsx, src/pages/demo/MainLayout.tsx, tests/components/MeasurementExplorer.test.tsx, tests/components/MeasurementPlot.test.tsx
Ref: https://github.com/zakodium-oss/analysis-ui-components/issues/313
=> feat: customize measurement stroke color

src/components/color-picker/gradient-select/GradientSelect.tsx
Closes: https://github.com/zakodium-oss/analysis-ui-components/issues/361
=> fix(gradient-select): allow to click on the chevron

src/app/hooks/file-loading.ts, src/components/dropdown-menu/DropdownMenu.tsx, src/components/dropdown-menu/MenuItems.tsx, src/components/dropdown-menu/useContextMenuPlacement.ts, src/components/hooks/index.ts, src/components/hooks/useModifiedPopper.ts, stories/components/dropdown.stories.tsx
- chore: return something from query callback
- feat: add useModifiedPopper hook
=> use popper

scripts/createData.mjs, src/app-data/state/appState.tsx, src/app-data/state/appStateActions.ts, src/app-data/state/data/AppData.ts, src/app-data/state/data/data.helpers.ts, src/app-data/state/data/getEmptyAppData.ts, src/app-data/state/data/index.ts, src/app-data/state/data/kinds.ts, src/app-data/state/settings/AppSettings.ts, src/app-data/state/settings/SettingsState.ts, src/app-data/state/settings/getEmptyAppSettings.ts, src/app-data/state/settings/getEmptySettingsState.ts, src/app-data/state/settings/index.ts, src/app-data/state/view/AppView.ts, src/app-data/state/view/getEmptyAppView.ts, src/app-data/state/view/getEmptyViewState.ts, src/app-data/state/view/index.ts, src/app/helpers/MeasurementPlot.tsx, src/app/kinds/iv/IvPlotView.tsx, src/app/kinds/mass/MassPlotView.tsx, src/app/panels/measurements/MeasurementsPanelAccordion.tsx, tests/components/MeasurementExplorer.test.tsx, tests/components/MeasurementPlot.test.tsx
- feat: add settings state
- refactor: remove "State" from data,view and settings
=> unselected opacity

src/app-data/loaders/biologicLoader.ts, src/app-data/loaders/cdfLoader.ts, src/app-data/loaders/jcampLoader.ts, src/app-data/loaders/proprietary/agilent/cary500Loader.ts, src/app-data/loaders/spcLoader.ts, src/app-data/loaders/utility/__tests__/getMeasurementInfoFromFile.test.ts, src/app-data/loaders/utility/getMeasurementInfoFromFile.ts, src/app-data/loaders/wdfLoader.ts, src/app-data/state/data/AppData.ts, src/app-data/state/index.ts, src/app/helpers/MeasurementPlot.tsx, src/app/helpers/react-plot.tsx, src/app/panels/measurements/MeasurementsPanel.tsx, stories/data/irMeasurement.json
- chore: export settings from state
- refactor: move all measurement info to the info field
=> Refactor measurement info

src/app-data/state/appStateActions.ts, src/app-data/state/producers/appStateProducer.ts, src/app-data/state/producers/measurements.ts, src/app/panels/measurements/MeasurementVisibilityToggle.tsx, src/app/panels/measurements/MeasurementsPanel.tsx
- fix: add table header to measurements panel
- feat: add column to toggle measurement visibility
=> Add table headers and change measurement visibility

src/app/panels/measurements/MeasurementsPanel.tsx, src/components/tabs/Tabs.tsx, src/components/tabs/TabsContext.tsx, stories/components/modal.stories.tsx, stories/components/tabs.stories.tsx
closes https://github.com/zakodium-oss/analysis-ui-components/issues/282
=> feat: opened in Tabs must contain opened item id

src/app-data/state/appStateActions.ts, src/app-data/state/producers/appStateProducer.ts, src/app-data/state/producers/measurements.ts, src/app/panels/measurements/MeasurementsPanel.tsx, src/app/panels/measurements/MeasurementsTable.tsx, src/components/table/Table.tsx
Close: https://github.com/zakodium-oss/analysis-ui-components/issues/380
Close: https://github.com/zakodium-oss/analysis-ui-components/issues/387
Close: https://github.com/zakodium-oss/analysis-ui-components/issues/390
=> update style of measurements table

src/components/dropdown-menu/DropdownMenu.tsx, src/components/dropdown-menu/MenuItems.tsx
close: https://github.com/zakodium-oss/analysis-ui-components/issues/372
=> fix: resolve error on close items

src/app/kinds/iv/plot-view/IvMeasurementsPlot.tsx, src/app/kinds/iv/plot-view/IvPlotView.tsx, src/app/kinds/iv/plot-view/IvSeries.tsx
Closes: https://github.com/zakodium-oss/analysis-ui-components/issues/413
=> feat: add crosshair to IV plot

src/app/kinds/iv/plot-view/IvMeasurementsPlot.tsx, src/app/panels/measurements/MeasurementCheckbox.tsx, src/app/panels/measurements/MeasurementColorPreview.tsx, src/app/panels/measurements/MeasurementsTable.tsx, src/components/color-picker/color-picker-dropdown/ColorPickerDropdown.tsx, src/pages/demo/main.tsx
- fix: add missing key to IvSeries
- chore: resolve emotion CSS warning
- refactor: move measurement checkbox to a separate file
- chore: add link to BIG-MAP app with small data
- refactor: simplify ColorPickerDropdown
- feat: allow to change measurement color from table
=> Change color from measurements table

src/app-data/state/data/data.helpers.ts, src/app-data/state/producers/measurements.ts, src/components/color-picker/index.ts, src/components/color-picker/palette.ts, src/components/color-picker/react-color/ColorPicker.tsx
Closes: https://github.com/zakodium-oss/analysis-ui-components/issues/405
=> fix: pick default colors from a palette while loading data

src/app-data/state/appStateActions.ts, src/app-data/state/producers/appStateProducer.ts, src/app-data/state/producers/measurements.ts, src/app/panels/measurements/MeasurementVisibilityToggle.tsx, src/app/panels/measurements/MeasurementsTable.tsx
close: https://github.com/zakodium-oss/analysis-ui-components/issues/391
=> feat: allow to change all measurements view at once

src/app-data/state/appStateActions.ts, src/app-data/state/data/data.helpers.ts, src/app-data/state/producers/appStateProducer.ts, src/app-data/state/producers/measurements.ts, src/app/panels/measurement-config/MeasurementConfigPanel.tsx, src/app/panels/measurement-config/MeasurementConfigPanelAccordion.tsx, src/pages/big-map/MainLayout.tsx
Close: https://github.com/zakodium-oss/analysis-ui-components/issues/410
=> feat: allow users to change multiple measurements color config

README.md, package-lock.json, package.json, src/app-data/loaders/loadMeasurements.ts, src/app-data/state/appStateActions.ts, src/app-data/state/producers/appStateProducer.ts, src/app-data/state/producers/measurements.ts, src/app-data/state/producers/plot-view/helpers/zoom.ts, src/app-data/state/producers/plot-view/plot-view.ts, src/app-data/state/view/AppView.ts, src/app-data/state/view/getEmptyAppView.ts, src/app/kinds/iv/plot-view/IvMeasurementsPlot.tsx, src/app/panels/SignalProcessingPanel.tsx, src/pages/big-map/helpers/loadFiles.ts, src/pages/demo/helpers/loadFiles.ts
- chore: update dependencies
- chore: rename "prefs" to "settings" in readme
- chore: log errors reported by loaders
- fix: compute missing variables min/max while loading measurements
- refactor: move IV measurement zoom to the view state
=> Move zoom behavior to the view state

src/app/kinds/iv/plot-view/IvPlotView.tsx
Parts of https://github.com/zakodium-oss/analysis-ui-components/issues/264
=> feat: add zoom out toolbar

.eslintrc.yml, src/app-data/loaders/biologicLoader.ts, src/app-data/state/appStateActions.ts, src/app-data/state/producers/appStateProducer.ts, src/app-data/state/producers/measurements.ts, src/app/panels/measurements/MeasurementsTable.tsx, src/components/button/ButtonGroup.tsx, src/components/button/index.ts
Close: https://github.com/zakodium-oss/analysis-ui-components/issues/414
Close: https://github.com/zakodium-oss/analysis-ui-components/issues/425
=> feat: remove header of the table to be a new row

src/app-data/helpers/index.ts, src/app-data/helpers/variables.ts, src/app-data/index.ts, src/app-data/state/appStateActions.ts, src/app-data/state/data/data.helpers.ts, src/app-data/state/producers/appStateProducer.ts, src/app-data/state/producers/measurements/addMeasurements.ts, src/app-data/state/producers/measurements/measurements.ts, src/app-data/state/producers/plot-view/helpers/zoom.ts, src/app-data/state/producers/plot-view/plot-view.ts, src/app-data/state/view/AppView.ts, src/app/helpers/MeasurementVariableSelect.tsx, src/app/helpers/getColorFromConfig.ts, src/app/helpers/index.ts, src/app/kinds/iv/plot-view/IvMeasurementsPlot.tsx, src/app/kinds/iv/plot-view/IvPlotVariablesSelector.tsx, src/app/kinds/iv/plot-view/IvPlotView.tsx, src/app/kinds/iv/plot-view/IvSeries.tsx, src/app/panels/measurement-config/MeasurementConfigPanel.tsx, src/app/panels/measurement-info/MeasurementInfoPanelAccordion.tsx, src/app/panels/measurements/MeasurementsTable.tsx, src/components/color-picker/gradient-select/GradientSelect.tsx, src/components/color-picker/preview/FixedGradientPreview.tsx
- fix: never hide measurement info panel
- fix: add confirm dialog to delete measurements
- feat: allow to select X and Y variables in IV measurements
- feat: display variable labels on IV axes
- feat: create MeasurementVariableSelect component
- refactor: rework MeasurementConfigPanel
=> Add variable selection

src/components/modal/ConfirmModal.tsx, src/components/modal/Modal.tsx
-  https://github.com/zakodium-oss/react-science/issues/459#issuecomment-1470163883
=> style: set shadow-box offset-y value with 0

src/components/dropdown-menu/DropdownMenu.tsx, stories/components/dropdown.stories.tsx
=> feat: adapt the DropdownMenu to accept 'as' prop to specify an element to be a wrapper

src/components/accordion/Accordion.tsx
Fixes: https://github.com/zakodium-oss/react-science/issues/487
=> fix: avoid double clicking issue

package-lock.json, package.json, src/components/forms/Select.tsx, stories/components/select.stories.tsx
Work in progress, I still need to figure out why keyboard navigation is not working.
=> feat: add select component

src/components/button/Button.tsx, stories/components/button.stories.tsx
Playing on opacity allow to not having to manage one more color and works well with every colours.
=> Disableable buttons

src/components/split-pane/SplitPane.tsx, stories/components/split-pane.stories.tsx
Fixes: https://github.com/zakodium-oss/react-science/issues/496
=> fix: set min width on percentage uncontrolled side

src/app/panels/measurement-info/MeasurementInfoPanel.tsx, src/components/index.ts, src/components/info-panel/InfoPanel.tsx, src/components/info-panel/index.ts, src/components/table/Table.tsx, stories/components/info-panel.stories.tsx
closes : https://github.com/zakodium-oss/react-science/issues/526
=> Implement InfoPanel Component

src/components/toolbar/PanelPreferencesToolbar.tsx, src/components/toolbar/index.ts, stories/components/panel-preferences-toolbar.stories.tsx
closes : https://github.com/zakodium-oss/react-science/issues/520
=> Implement PanelPreferencesToolbar component

.storybook/main.ts, package-lock.json, package.json
closes : https://github.com/zakodium-oss/react-science/issues/533
=> View stories' source code

src/components/modal/ConfirmModal.tsx, stories/components/modal.stories.tsx
refs : https://github.com/cheminfo/nmrium/issues/2609
refs : https://github.com/cheminfo/nmrium/pull/2618
=> Improve Confirm Modal Style

src/components/modal/Modal.tsx
closes :  https://github.com/zakodium-oss/react-science/issues/540
=> Remove Modal outline on focus

src/components/split-pane/SplitPane.tsx, src/components/split-pane/useSplitPaneSize.tsx
- Adjusting the size of the splitter by touch and move. 
- Close the splitter by touching it with two fingers.
=> feat: improve splitter component to work on touch devices 

src/components/info-panel/InfoPanel.tsx, stories/components/info-panel.stories.tsx
closes : https://github.com/zakodium-oss/react-science/issues/563
=> 563 info panel and smart ordering

src/components/info-panel/InfoPanel.tsx, src/components/value-renderers/Number.tsx, stories/components/info-panel.stories.tsx
=> Fix boolean and zero values in infopanel

babel.config.js, package-lock.json, package.json, src/app/hooks/file-loading.ts
- chore: fix ts build error
- chore: fix webpack issues
=> fix TS esm build and storybook build

src/components/toolbar/Toolbar.tsx
we try to fix the issue of the toolbar item width
=> fix: toolbar item width

.eslintignore, src/app/kinds/ir/IrPeaksPanel.tsx, src/app/panels/SignalProcessingPanel.tsx, src/components/info-panel/InfoPanel.tsx, src/components/table/Table.tsx, src/components/table/TableHeader.tsx, src/components/table/TableRow.tsx, src/components/table/tableContext.ts, stories/components/drop-zone.stories.tsx, stories/components/table.stories.tsx
closes #583
- Replace "Title" with "Header" to make the bordered property work in the `HTMLTable` header
- Add the color prop for `StyledTable`
- Remove `Controls` story (duplicate of `Control`)
=> Use blueprintjs HTMLTable

src/components/toolbar/PanelPreferencesToolbar.tsx, src/components/toolbar/Toolbar.tsx, stories/components/panel-header.stories.tsx
closes : https://github.com/zakodium-oss/react-science/issues/627
=> Toolbar in panel header story is broken

src/app/panels/measurements/MeasurementsPanel.tsx, src/app/panels/measurements/MeasurementsTable.tsx
=> Improve layout of tabs

src/components/color-picker/color-picker-dropdown/ColorPickerDropdown.tsx, stories/components/color-picker-dropdown.stories.tsx
closes : https://github.com/zakodium-oss/react-science/issues/638
=> 638 clicking outside to close the color picker is closing the modal

src/components/toolbar/Toolbar.tsx
=> Fix popover toolbar item layout

stories/app/measurements/measurement-plot.stories.tsx
Closes : https://github.com/zakodium-oss/react-science/issues/660
=> Fix measurement-plot story

src/app/panels/measurements/MeasurementCheckbox.tsx, src/app/panels/measurements/MeasurementColorPreview.tsx, src/app/panels/measurements/MeasurementVisibilityToggle.tsx, src/app/panels/measurements/MeasurementsPanel.tsx, src/app/panels/measurements/MeasurementsPanelAccordion.tsx, src/app/panels/measurements/MeasurementsTable.tsx, src/app/panels/measurements/index.ts, src/app/panels/measurements/measurementPanelContext.tsx, src/components/toolbar/PanelPreferencesToolbar.tsx, src/pages/demo/MainLayout.tsx
Closes : https://github.com/zakodium-oss/react-science/issues/650
Closes : https://github.com/zakodium-oss/react-science/issues/651
=> Use stacked panel for measurement info panel

src/components/toolbar/Toolbar.tsx, src/components/toolbar/toolbarContext.ts, stories/components/toolbar.stories.tsx
=> Add hover option for popover toolbar trigger

src/components/header/PanelHeader.tsx
closes : https://github.com/zakodium-oss/react-science/issues/671
=> Remove useEffect from PanelHeader

src/components/info-panel/InfoPanel.tsx, stories/components/info-panel.stories.tsx
Closes : https://github.com/zakodium-oss/react-science/issues/640
=> Improve info-panel design

src/app/about/AboutDialogToolbarButton.tsx, src/app/kinds/iv/plot-view/IvPlotView.tsx, src/components/fullscreen/FullscreenToolbarButton.tsx, src/components/toolbar/PanelPreferencesToolbar.tsx, src/components/toolbar/Toolbar.tsx, src/pages/demo/MainLayout.tsx, stories/components/accordion.stories.tsx, stories/components/dialog.stories.tsx, stories/components/header.stories.tsx, stories/components/panel-header.stories.tsx, stories/components/toolbar.stories.tsx
=> feat!: improve toolbar tip

src/components/info-panel/InfoPanel.tsx, stories/components/info-panel.stories.tsx
closes : https://github.com/zakodium-oss/react-science/issues/706
=> InfoPanel responsive

src/app/panels/measurement-info/MeasurementInfoPanelAccordion.tsx, src/pages/demo/MainLayout.tsx
closes : https://github.com/zakodium-oss/react-science/issues/707
=> Add MeasurementInfo in the demo

src/components/root-layout/RootLayout.tsx, src/pages/demo/MainLayout.tsx
closes : https://github.com/zakodium-oss/react-science/issues/688
=> Remove useless divs in RootLayout

src/app/panels/SignalProcessingPanel.tsx, src/components/info-panel/InfoPanel.tsx, src/components/logger/FifoLoggerDialog.tsx, src/components/table/Table.tsx, src/components/table/TableHeader.tsx, src/components/table/TableRow.tsx, src/components/table/tableContext.ts, stories/components/table.stories.tsx
closes https://github.com/zakodium-oss/react-science/issues/721
=> Fix InfoPanel Table Row

package-lock.json, package.json
resolves a React warning about defaultProps
=> fix: update react-plot

src/components/header/PanelHeader.tsx, src/components/index.ts, src/components/info-panel/InfoPanel.tsx, src/components/selected-total/SelectedTotal.tsx, src/components/selected-total/index.ts
closes : https://github.com/zakodium-oss/react-science/issues/765
=> feat: implement select-total component

src/components/toolbar/Toolbar.tsx, stories/components/toolbar.stories.tsx
- **docs: put toolbar in flex container in control story**
- **fix: ensure popover toolbar item does not grow**
=> fix: ensure popover toolbar item does not grow when in flex container

src/components/activity_bar/activity_bar.tsx, src/components/activity_panel/activity_panel.tsx, src/components/split-pane/SplitPane.tsx, stories/components/activity_bar.stories.tsx, stories/components/toolbar.stories.tsx
- **feat: improve activity bar layout**
- **docs: rename and move stories**
=> chore: improve activity bar and panel layout

src/components/accordion/accordion.tsx, src/components/accordion/accordion_context.provider.tsx, src/components/accordion/accordion_context.state.ts, src/components/accordion/accordion_context.ts, stories/components/accordion.stories.tsx
Opt into not rendering hidden accordion item's children at all.
=> feat: add unmountChildren prop to Accordion and Accordion.Item

src/components/table/table_root.tsx
Closes: https://github.com/zakodium-oss/react-science/issues/802
=> fix(table_root): show border when table is sticky

src/components/color-picker/gradient_select/gradient_select.tsx
=> refactor(gradiant_select): change css to use styled

src/components/accordion/accordion.tsx
=> refactor(Accordion): change css to use styled

src/components/toolbar/Toolbar.tsx
=> refactor(Toolbar): change css to use styled

src/components/header/PanelHeader.tsx
=> refactor(PanelHeader): change css to use styled

src/components/toolbar/PanelPreferencesToolbar.tsx
=> refactor(PanelPreferencesToolbar): change css to use styled

stories/components/split-pane.stories.tsx
=> docs(SplitPane): change css to use styled

stories/components/button.stories.tsx
=> docs(Button): change css to use styled

stories/components/context-menu.stories.tsx
=> docs(ContextMenu): change css to use styled

package-lock.json, package.json, src/app/panels/measurements/MeasurementsPanel.tsx, src/app/panels/measurements/MeasurementsPanelAccordion.tsx, src/components/accordion/accordion.tsx, src/components/button/Button.tsx, src/components/color-picker/gradient_select/gradient_select.tsx, src/components/dialog/ConfirmDialog.tsx, src/components/forms/radio-button-group/RadioButton.tsx, src/components/forms/radio-button-group/RadioButtonGroup.tsx, src/components/header/Header.tsx, src/components/header/PanelHeader.tsx, src/components/info-panel/InfoPanel.tsx, src/components/logger/FifoLoggerDialog.tsx, src/components/split-pane/SplitPane.tsx, src/components/table/table_root.tsx, src/components/toolbar/PanelPreferencesToolbar.tsx, src/components/toolbar/Toolbar.tsx, src/components/value-renderers/Color.tsx, src/components/value-renderers/Text.tsx, src/components/value-renderers/Title.tsx, stories/components/button.stories.tsx, stories/components/context-menu.stories.tsx, stories/components/dialog.stories.tsx, stories/components/input.stories.tsx, stories/components/menus.stories.tsx, stories/components/panel-header.stories.tsx, stories/components/split-pane.stories.tsx, stories/components/tabs.stories.tsx
=> chore: remove emotion/react

src/components/accordion/accordion.tsx, src/components/toolbar/TooltipHelpContent.tsx
- **fix: accordion color**
- **fix: resolve React warning about `first-child` selector**
=> Small fixes for last release

src/components/split-pane/SplitPane.tsx, stories/components/split-pane.stories.tsx
Closes: https://github.com/zakodium-oss/react-science/issues/883
=> docs(SplitPane): correct documentation of closeThreshold prop

src/components/accordion/accordion.tsx
And use gray colors from the blueprint library
=> feat(accordion): highlight interactivity by changing the header's color

src/components/table/index.ts, src/components/table/table_body.tsx, src/components/table/table_header_cell.tsx, src/components/table/table_root.tsx, src/components/table/table_row_cell.tsx, stories/components/table.stories.tsx, stories/components/table_columns.tsx, stories/react-table.d.ts
- **feat(Table): add support for `thStyle` in column meta**
- **feat(Table): add `tdStyle` prop**
=> Table QoL improvements

src/components/dialog/ConfirmDialog.tsx, src/components/info-panel/InfoPanel.tsx, src/components/table/table_root.tsx, src/components/utils/shouldForwardPropExcept.ts, stories/components/tabs.stories.tsx, stories/components/utils/ShouldForwardProps.stories.tsx
Closes: https://github.com/zakodium-oss/react-science/issues/896
=> feat: create shouldForwardPropExcept utils

.storybook/preview.ts, src/components/index.ts, src/components/svg/index.ts, src/components/svg/styled/svg_styled_line.stories.tsx, src/components/svg/styled/svg_styled_line.tsx, src/components/svg/styled/svg_styled_path.stories.tsx, src/components/svg/styled/svg_styled_path.tsx, src/components/svg/styled/svg_styled_text.stories.tsx, src/components/svg/styled/svg_styled_text.tsx, src/components/svg/styled/svg_styled_types.ts, src/components/svg/styled/svg_styled_utils.ts
https://938-component-to-select-svg.react-science.pages.dev/stories/?path=/story/components-svg-svgstyledline--control
=> User configuration for SVG lines, paths, and text
